apiVersion: apps/v1
kind: Deployment
metadata:
  name: mini-finance-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mini-finance-app
  template:
    metadata:
      labels:
        app: mini-finance-app
    spec:
      containers:
      - name: mini-finance-app
        image: mini-finance-app:local
        imagePullPolicy: IfNotPresent # Important for local images
        ports:
        - containerPort: 80
