apiVersion: v1
kind: Service
metadata:
  name: mini-finance-app-service
spec:
  type: NodePort
  selector:
    app: mini-finance-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      # NodePort must be in the range 30000-32767
      nodePort: 30080
